/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mavenrulewriter;

/**
 *
 * @author Efisch
 */
public class HistoricProcedure extends javax.swing.JFrame implements ConditionFrame{

    /**
     * Creates new form HistoricProcedure
     */
    Detail editTarget;
     MavenRuleFrontend myParent; 
    public HistoricProcedure(MavenRuleFrontend myParentIn) {
        myParent = myParentIn;
        initComponents();
    }
 public HistoricProcedure(MavenRuleFrontend myParentIn, HistoricProcedureDetail n) {
        myParent = myParentIn;
        editTarget = n;
       
        
        initComponents();
       
         int timeCalc = n.getMinDays();
         if(timeCalc>0){
             HistoricProcedureTimeFrameFutureBox.setSelectedIndex(1);
         } else {
             timeCalc *=-1;
         }
         HistoricProcedureTimeFrameYearSpinner.setValue(timeCalc/365);
        timeCalc%=365;
         HistoricProcedureTimeFrameMonthSpinner.setValue(timeCalc/30);
         timeCalc%=30;
         HistoricProcedureTimeFrameDaySpinner.setValue(timeCalc);
          timeCalc = n.getMaxDays();
          if(timeCalc>0){
             HistoricProcedureTimeFrameFutureBox1.setSelectedIndex(1);
         } else {
             timeCalc *=-1;
         }
        HistoricProcedureTimeFrameYearSpinner1.setValue(timeCalc/365);
        timeCalc%=365;
         HistoricProcedureTimeFrameMonthSpinner1.setValue(timeCalc/30);
         timeCalc%=30;
         HistoricProcedureTimeFrameDaySpinner1.setValue(timeCalc);
         HistoricProcedureCPTField.setText(n.CPT+"");
         HistoricProcedureNegationBox.setSelected(n.negative);
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        HistoricProcedureTypeLabel = new javax.swing.JLabel();
        HistoricProcedureTimeFrameYearSpinner = new javax.swing.JSpinner();
        jLabel = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        OKButton = new javax.swing.JButton();
        HistoricProcedureTimeFrameMonthSpinner = new javax.swing.JSpinner();
        jLabel32 = new javax.swing.JLabel();
        HistoricProcedureTimeFrameDaySpinner = new javax.swing.JSpinner();
        jLabel33 = new javax.swing.JLabel();
        HistoricProcedureTimeFrameYearSpinner1 = new javax.swing.JSpinner();
        HistoricProcedureTimeFrameFutureBox = new javax.swing.JComboBox();
        HistoricProcedureCPTField = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        HistoricProcedureNegationBox = new javax.swing.JCheckBox();
        HistoricProcedureTimeFrameMonthSpinner1 = new javax.swing.JSpinner();
        jLabel36 = new javax.swing.JLabel();
        HistoricProcedureTimeFrameDaySpinner1 = new javax.swing.JSpinner();
        jLabel37 = new javax.swing.JLabel();
        HistoricProcedureTimeFrameFutureBox1 = new javax.swing.JComboBox();
        jLabel38 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        HistoricProcedureTypeLabel.setText("Use Rule Only if Patient Has Undergone Procedure (CPT CODE)");

        jLabel.setText("Within the Following Time Frame");

        jLabel31.setText("Years");

        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        jLabel32.setText("Months");

        jLabel33.setText("Days");

        HistoricProcedureTimeFrameFutureBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Before", "After" }));

        jLabel34.setText("Present");

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel35.setText("Until");

        HistoricProcedureNegationBox.setText("Disallow Procedure");
        HistoricProcedureNegationBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoricProcedureNegationBoxActionPerformed(evt);
            }
        });

        jLabel36.setText("Years");

        jLabel37.setText("Months");

        HistoricProcedureTimeFrameFutureBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Before", "After" }));

        jLabel38.setText("Days");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Time Frame");

        jLabel39.setText("Present");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Create New Historic Procedure Criterion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(HistoricProcedureTimeFrameYearSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel31)
                                .addGap(17, 17, 17)
                                .addComponent(HistoricProcedureTimeFrameMonthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel32))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(HistoricProcedureTimeFrameYearSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(HistoricProcedureTimeFrameMonthSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jLabel37)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(HistoricProcedureTimeFrameDaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HistoricProcedureTimeFrameFutureBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel34))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(HistoricProcedureTimeFrameDaySpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HistoricProcedureTimeFrameFutureBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel39))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addComponent(jLabel35)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(HistoricProcedureTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(HistoricProcedureCPTField, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(jLabel12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(HistoricProcedureNegationBox)))
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(31, 31, 31)
                        .addComponent(OKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(325, 325, 325))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(216, 216, 216))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HistoricProcedureCPTField)
                    .addComponent(HistoricProcedureTypeLabel)
                    .addComponent(jLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HistoricProcedureNegationBox)
                .addGap(14, 14, 14)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(HistoricProcedureTimeFrameMonthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel32)
                        .addComponent(HistoricProcedureTimeFrameDaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel33)
                        .addComponent(HistoricProcedureTimeFrameFutureBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel34))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(HistoricProcedureTimeFrameYearSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel31)))
                .addGap(18, 18, 18)
                .addComponent(jLabel35)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(HistoricProcedureTimeFrameFutureBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38)
                    .addComponent(HistoricProcedureTimeFrameDaySpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(jLabel36)
                    .addComponent(HistoricProcedureTimeFrameYearSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HistoricProcedureTimeFrameMonthSpinner1))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OKButton)
                    .addComponent(jButton4))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        Detail n = getDetail();
        if (editTarget!=null){
            n.name = editTarget.name;
        } 
        myParent.recieveDetail(n);
        this.dispose();
    }//GEN-LAST:event_OKButtonActionPerformed

    private void HistoricProcedureNegationBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoricProcedureNegationBoxActionPerformed
         if(!HistoricProcedureNegationBox.isSelected())
            HistoricProcedureTypeLabel.setText("Use Rule Only if Patient Has Undergone Procedure (CPT CODE)");
        else
            HistoricProcedureTypeLabel.setText("Do Not Use Rule if Patient Has Undergone Procedure (CPT CODE)");
    }//GEN-LAST:event_HistoricProcedureNegationBoxActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.myParent.setEnabled(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HistoricProcedureCPTField;
    private javax.swing.JCheckBox HistoricProcedureNegationBox;
    private javax.swing.JSpinner HistoricProcedureTimeFrameDaySpinner;
    private javax.swing.JSpinner HistoricProcedureTimeFrameDaySpinner1;
    private javax.swing.JComboBox HistoricProcedureTimeFrameFutureBox;
    private javax.swing.JComboBox HistoricProcedureTimeFrameFutureBox1;
    private javax.swing.JSpinner HistoricProcedureTimeFrameMonthSpinner;
    private javax.swing.JSpinner HistoricProcedureTimeFrameMonthSpinner1;
    private javax.swing.JSpinner HistoricProcedureTimeFrameYearSpinner;
    private javax.swing.JSpinner HistoricProcedureTimeFrameYearSpinner1;
    private javax.swing.JLabel HistoricProcedureTypeLabel;
    private javax.swing.JButton OKButton;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    // End of variables declaration//GEN-END:variables

    @Override
    public Detail getDetail() {
        HistoricProcedureDetail n = new HistoricProcedureDetail("");
        n.setNegative(HistoricProcedureNegationBox.isSelected());
        n.frameMin = 365*(int)HistoricProcedureTimeFrameYearSpinner.getValue();
        
        n.frameMin +=30*(int)HistoricProcedureTimeFrameMonthSpinner.getValue();
        
        n.frameMin +=(int)HistoricProcedureTimeFrameDaySpinner.getValue();
      
        n.frameMax = 365*(int)HistoricProcedureTimeFrameYearSpinner1.getValue();
       
        n.frameMax += 30*(int)HistoricProcedureTimeFrameMonthSpinner1.getValue();
        
        n.frameMax += (int)HistoricProcedureTimeFrameDaySpinner1.getValue();
     
        if (HistoricProcedureTimeFrameFutureBox.getSelectedItem().toString().equals("Before")){
            n.frameMin*=-1;
        }
        if (HistoricProcedureTimeFrameFutureBox1.getSelectedItem().toString().equals("Before")){
            n.frameMax*=-1;
        }
        n.CPT = Integer.parseInt(HistoricProcedureCPTField.getText());
        
        return n;
        
    }

   
}
