({
    mainConfigFile: '../www_modular/js/main.js',
    baseUrl: '../www_modular/js',
    name: 'main',
    out: '../www_modular/js/main-built.js',
    removeCombined: true,
    findNestedDependencies: true,
    generateSourceMaps: true,
    preserveLicenseComments: false,
    optimize: 'uglify2',
    paths: {
        'ace': 'empty:',
        'jsplumb': 'empty:',
        'bootstrap': 'empty:',
        'jquery': 'empty:',
        'jquery_ui': 'empty:',
        'underscore': 'empty:',
        'backbone': 'empty:',
        'ckeditor': 'empty:',
        'amcharts': 'empty:',
        'bootstrapswitch': 'empty:',
        '/services/recaptcha': 'empty:'
    },
    shim: {
        ace: {
             deps: ['jquery', 'jquery_ui','bootstrap']
        },
        bootstrap: {
            deps: ['jquery']
        },
        jsplumb: {
            deps: ['jquery', 'jquery_ui']
        },
        fullCalendar: {
            deps: ['jquery', 'moment', 'jquery_ui']
        },
        jquery_ui: {
            deps: ['jquery'],
        },
        amchartspie: { deps: ['amcharts'], exports: 'AmCharts', init: function () {
            AmCharts.isReady = true;
        }},
        amchartsserial: { deps: ['amcharts'], exports: 'AmCharts', init: function () {
            AmCharts.isReady = true;
        }},
        amchartslight: { deps: ['amcharts'], exports: 'AmCharts', init: function () {
            AmCharts.isReady = true;
        }},
    },
    inlineText: true,
    exclude: [
        'libs/amcharts/serial',
        'libs/fullCalendar/fullcalendar.min',
        'libs/fullCalendar/moment.min'
    ],
    include: [
        '../ace/assets/js/ace-extra.js',
        '../ace/assets/js/ace-elements.js',
        '../ace/assets/js/ace.js',
        '../ace/assets/js/jquery-ui.custom.js',
        '../ace/assets/js/jquery.ui.touch-punch.js',
        '../ace/assets/js/jquery.easypiechart.js',
        '../ace/assets/js/jquery.sparkline.js',
        '../ace/assets/js/flot/jquery.flot.js',
        '../ace/assets/js/flot/jquery.flot.pie.js',
        '../ace/assets/js/flot/jquery.flot.resize.js',
        '../ace/assets/js/ace/elements.scroller.js',
        '../ace/assets/js/ace/elements.colorpicker.js',
        '../ace/assets/js/ace/elements.fileinput.js',
        '../ace/assets/js/ace/elements.typeahead.js',
        '../ace/assets/js/ace/elements.wysiwyg.js',
        '../ace/assets/js/ace/elements.spinner.js',
        '../ace/assets/js/ace/elements.treeview.js',
        '../ace/assets/js/ace/elements.wizard.js',
        '../ace/assets/js/ace/elements.aside.js',
        '../ace/assets/js/ace/ace.js',
        '../ace/assets/js/ace/ace.ajax-content.js',
        '../ace/assets/js/ace/ace.touch-drag.js',
        '../ace/assets/js/ace/ace.sidebar.js',
        '../ace/assets/js/ace/ace.sidebar-scroll-1.js',
        '../ace/assets/js/ace/ace.submenu-hover.js',
        '../ace/assets/js/ace/ace.widget-box.js',
        '../ace/assets/js/ace/ace.settings.js',
        '../ace/assets/js/ace/ace.settings-rtl.js',
        '../ace/assets/js/ace/ace.settings-skin.js',
        '../ace/assets/js/ace/ace.widget-on-reload.js',
        '../ace/assets/js/ace/ace.searchbox-autocomplete.js',
        'pathway/modalViews/ruleWizard',
        'pathway/modalViews/sendProtocol',
        'pathway/modalViews/editNode',
        'pathway/modalViews/sendFollowups',
        'pathway/modalViews/detailEditor_archaic',
        'pathway/modalViews/nodeEditor',
        'pathway/modalViews/newPathway',
        'pathway/modalViews/detailEditor',
        'pathway/modalViews/sidePanelEditor',
        'pathway/modalViews/DeleteDialog',
        'pathway/modalViews/protocolEditor',
        'pathway/internalViews/detailSelector',
        'pathway/internalViews/detailSearchBox',
        'pathway/internalViews/triggerNode',
        'pathway/internalViews/treeNodeActionSet',
        'pathway/internalViews/treeNode',
        'pathway/internalViews/protocolNode',
        'pathway/internalViews/detailGroup',
        'pathway/internalViews/detailListBox',
        'pathway/internalViews/multiSelectSearch',
        'pathway/Helpers',
        'pathway/singleRows/pathRow',
        'pathway/models/treeModel',
        'pathway/models/nodeModel',
        'pathway/models/pathwayCollection',
        'globalmodels/summaryModel',
        'globalmodels/patientModel',
        'globalmodels/spendingModel',
        'globalmodels/orderCollection',
        'globalmodels/customerCollection',
        'globalmodels/scrollCollection',
        'globalmodels/auditCollection',
        'globalmodels/patientCollection',
        'globalmodels/userCollection',
        'globalmodels/histogramModel',
        'globalmodels/contextModel',
        'globalmodels/alertCollection',
        'widgets/welcome',
        'widgets/patientSearch',
        'widgets/datepicker-calendar',
        'widgets/patientList',
        'widgets/customerCreation',
        'widgets/providerProfile',
        'widgets/userList',
        'widgets/login',
        'widgets/evidence',
        'widgets/encounterSummary',
        'widgets/auditList',
        'widgets/costtable',
        'widgets/customerList',
        'widgets/costdonut',
        'widgets/patientInfo',
        'widgets/alertList',
        'widgets/widgetModal',
        'widgets/spend_histogram',
        'widgets/maveninfo',
        'widgets/adminSettings',
        'widgets/pathway',
        'widgets/datepicker-chart',
        'widgets/settings',
        'widgets/topBanner',
        'widgets/orderList',
        'widgets/pathway/toolbar.js',
        'widgets/pathway/TreeView.js',
        'Helpers',
        'singleRow/customerRow',
        'singleRow/userRow',
        'singleRow/orderRow',
        'singleRow/auditRow',
        'singleRow/alertRow',
        'singleRow/reminderRow',
        'singleRow/patientRow',
        'text'

    ]
})
