//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MavenAsDemo.Unity {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UnityFault", Namespace="http://schemas.datacontract.org/2004/07/Allscripts.UAI.Unity.UnityService")]
    [System.SerializableAttribute()]
    public partial class UnityFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MagicInput", Namespace="http://schemas.datacontract.org/2004/07/Allscripts.UAI.Unity.UnityService")]
    [System.SerializableAttribute()]
    public partial class MagicInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatientIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Parameter1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Parameter2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Parameter3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Parameter4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Parameter5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Parameter6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Action {
            get {
                return this.ActionField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionField, value) != true)) {
                    this.ActionField = value;
                    this.RaisePropertyChanged("Action");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Appname {
            get {
                return this.AppnameField;
            }
            set {
                if ((object.ReferenceEquals(this.AppnameField, value) != true)) {
                    this.AppnameField = value;
                    this.RaisePropertyChanged("Appname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string AppUserID {
            get {
                return this.AppUserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AppUserIDField, value) != true)) {
                    this.AppUserIDField = value;
                    this.RaisePropertyChanged("AppUserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string PatientID {
            get {
                return this.PatientIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientIDField, value) != true)) {
                    this.PatientIDField = value;
                    this.RaisePropertyChanged("PatientID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Parameter1 {
            get {
                return this.Parameter1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Parameter1Field, value) != true)) {
                    this.Parameter1Field = value;
                    this.RaisePropertyChanged("Parameter1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Parameter2 {
            get {
                return this.Parameter2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Parameter2Field, value) != true)) {
                    this.Parameter2Field = value;
                    this.RaisePropertyChanged("Parameter2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string Parameter3 {
            get {
                return this.Parameter3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Parameter3Field, value) != true)) {
                    this.Parameter3Field = value;
                    this.RaisePropertyChanged("Parameter3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string Parameter4 {
            get {
                return this.Parameter4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Parameter4Field, value) != true)) {
                    this.Parameter4Field = value;
                    this.RaisePropertyChanged("Parameter4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string Parameter5 {
            get {
                return this.Parameter5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Parameter5Field, value) != true)) {
                    this.Parameter5Field = value;
                    this.RaisePropertyChanged("Parameter5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string Parameter6 {
            get {
                return this.Parameter6Field;
            }
            set {
                if ((object.ReferenceEquals(this.Parameter6Field, value) != true)) {
                    this.Parameter6Field = value;
                    this.RaisePropertyChanged("Parameter6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetTokenInput", Namespace="http://schemas.datacontract.org/2004/07/Allscripts.UAI.Unity.UnityService")]
    [System.SerializableAttribute()]
    public partial class GetTokenInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginalTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginalToken {
            get {
                return this.OriginalTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalTokenField, value) != true)) {
                    this.OriginalTokenField = value;
                    this.RaisePropertyChanged("OriginalToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetTokenJsonInput", Namespace="http://schemas.datacontract.org/2004/07/Allscripts.UAI.Unity.UnityService")]
    [System.SerializableAttribute()]
    public partial class GetTokenJsonInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginalTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginalToken {
            get {
                return this.OriginalTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginalTokenField, value) != true)) {
                    this.OriginalTokenField = value;
                    this.RaisePropertyChanged("OriginalToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetireTokenInput", Namespace="http://schemas.datacontract.org/2004/07/Allscripts.UAI.Unity.UnityService")]
    [System.SerializableAttribute()]
    public partial class RetireTokenInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Appname {
            get {
                return this.AppnameField;
            }
            set {
                if ((object.ReferenceEquals(this.AppnameField, value) != true)) {
                    this.AppnameField = value;
                    this.RaisePropertyChanged("Appname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetireTokenJsonInput", Namespace="http://schemas.datacontract.org/2004/07/Allscripts.UAI.Unity.UnityService")]
    [System.SerializableAttribute()]
    public partial class RetireTokenJsonInput : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Appname {
            get {
                return this.AppnameField;
            }
            set {
                if ((object.ReferenceEquals(this.AppnameField, value) != true)) {
                    this.AppnameField = value;
                    this.RaisePropertyChanged("Appname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.allscripts.com/Unity", ConfigurationName="Unity.IUnityService")]
    public interface IUnityService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.allscripts.com/Unity/IUnityService/Magic", ReplyAction="http://www.allscripts.com/Unity/IUnityService/MagicResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MavenAsDemo.Unity.UnityFault), Action="http://www.allscripts.com/Unity/IUnityService/MagicUnityFaultFault", Name="UnityFault", Namespace="http://schemas.datacontract.org/2004/07/Allscripts.UAI.Unity.UnityService")]
        System.Data.DataSet Magic(string Action, string UserID, string Appname, string PatientID, string Token, string Parameter1, string Parameter2, string Parameter3, string Parameter4, string Parameter5, string Parameter6, byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.allscripts.com/Unity/IUnityService/Magic", ReplyAction="http://www.allscripts.com/Unity/IUnityService/MagicResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> MagicAsync(string Action, string UserID, string Appname, string PatientID, string Token, string Parameter1, string Parameter2, string Parameter3, string Parameter4, string Parameter5, string Parameter6, byte[] data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.allscripts.com/Unity/IUnityService/ReturnMagicJSON", ReplyAction="http://www.allscripts.com/Unity/IUnityService/ReturnMagicJSONResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MavenAsDemo.Unity.UnityFault), Action="http://www.allscripts.com/Unity/IUnityService/ReturnMagicJSONUnityFaultFault", Name="UnityFault", Namespace="http://schemas.datacontract.org/2004/07/Allscripts.UAI.Unity.UnityService")]
        System.IO.Stream ReturnMagicJSON(MavenAsDemo.Unity.MagicInput o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.allscripts.com/Unity/IUnityService/ReturnMagicJSON", ReplyAction="http://www.allscripts.com/Unity/IUnityService/ReturnMagicJSONResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> ReturnMagicJSONAsync(MavenAsDemo.Unity.MagicInput o);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.allscripts.com/Unity/IUnityService/GetSecurityToken", ReplyAction="http://www.allscripts.com/Unity/IUnityService/GetSecurityTokenResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MavenAsDemo.Unity.UnityFault), Action="http://www.allscripts.com/Unity/IUnityService/GetSecurityTokenUnityFaultFault", Name="UnityFault", Namespace="http://schemas.datacontract.org/2004/07/Allscripts.UAI.Unity.UnityService")]
        string GetSecurityToken(string Username, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.allscripts.com/Unity/IUnityService/GetSecurityToken", ReplyAction="http://www.allscripts.com/Unity/IUnityService/GetSecurityTokenResponse")]
        System.Threading.Tasks.Task<string> GetSecurityTokenAsync(string Username, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.allscripts.com/Unity/IUnityService/GetValidSecurityToken", ReplyAction="http://www.allscripts.com/Unity/IUnityService/GetValidSecurityTokenResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(MavenAsDemo.Unity.UnityFault), Action="http://www.allscripts.com/Unity/IUnityService/GetValidSecurityTokenUnityFaultFaul" +
            "t", Name="UnityFault", Namespace="http://schemas.datacontract.org/2004/07/Allscripts.UAI.Unity.UnityService")]
        string GetValidSecurityToken(string Username, string Password, string originalToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.allscripts.com/Unity/IUnityService/GetValidSecurityToken", ReplyAction="http://www.allscripts.com/Unity/IUnityService/GetValidSecurityTokenResponse")]
        System.Threading.Tasks.Task<string> GetValidSecurityTokenAsync(string Username, string Password, string originalToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.allscripts.com/Unity/IUnityService/GetValidSecurityTokenPost", ReplyAction="http://www.allscripts.com/Unity/IUnityService/GetValidSecurityTokenPostResponse")]
        System.IO.Stream GetValidSecurityTokenPost(MavenAsDemo.Unity.GetTokenInput ti);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.allscripts.com/Unity/IUnityService/GetValidSecurityTokenPost", ReplyAction="http://www.allscripts.com/Unity/IUnityService/GetValidSecurityTokenPostResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetValidSecurityTokenPostAsync(MavenAsDemo.Unity.GetTokenInput ti);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.allscripts.com/Unity/IUnityService/GetTokenJsonPost", ReplyAction="http://www.allscripts.com/Unity/IUnityService/GetTokenJsonPostResponse")]
        System.IO.Stream GetTokenJsonPost(MavenAsDemo.Unity.GetTokenJsonInput ti);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.allscripts.com/Unity/IUnityService/GetTokenJsonPost", ReplyAction="http://www.allscripts.com/Unity/IUnityService/GetTokenJsonPostResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetTokenJsonPostAsync(MavenAsDemo.Unity.GetTokenJsonInput ti);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.allscripts.com/Unity/IUnityService/RetireSecurityTokenPost", ReplyAction="http://www.allscripts.com/Unity/IUnityService/RetireSecurityTokenPostResponse")]
        void RetireSecurityTokenPost(MavenAsDemo.Unity.RetireTokenInput ri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.allscripts.com/Unity/IUnityService/RetireSecurityTokenPost", ReplyAction="http://www.allscripts.com/Unity/IUnityService/RetireSecurityTokenPostResponse")]
        System.Threading.Tasks.Task RetireSecurityTokenPostAsync(MavenAsDemo.Unity.RetireTokenInput ri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.allscripts.com/Unity/IUnityService/RetireTokenJsonPost", ReplyAction="http://www.allscripts.com/Unity/IUnityService/RetireTokenJsonPostResponse")]
        void RetireTokenJsonPost(MavenAsDemo.Unity.RetireTokenJsonInput ri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.allscripts.com/Unity/IUnityService/RetireTokenJsonPost", ReplyAction="http://www.allscripts.com/Unity/IUnityService/RetireTokenJsonPostResponse")]
        System.Threading.Tasks.Task RetireTokenJsonPostAsync(MavenAsDemo.Unity.RetireTokenJsonInput ri);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.allscripts.com/Unity/IUnityService/RetireSecurityToken", ReplyAction="http://www.allscripts.com/Unity/IUnityService/RetireSecurityTokenResponse")]
        void RetireSecurityToken(string Token, string Appname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.allscripts.com/Unity/IUnityService/RetireSecurityToken", ReplyAction="http://www.allscripts.com/Unity/IUnityService/RetireSecurityTokenResponse")]
        System.Threading.Tasks.Task RetireSecurityTokenAsync(string Token, string Appname);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUnityServiceChannel : MavenAsDemo.Unity.IUnityService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UnityServiceClient : System.ServiceModel.ClientBase<MavenAsDemo.Unity.IUnityService>, MavenAsDemo.Unity.IUnityService {
        
        public UnityServiceClient() {
        }
        
        public UnityServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UnityServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UnityServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UnityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Magic(string Action, string UserID, string Appname, string PatientID, string Token, string Parameter1, string Parameter2, string Parameter3, string Parameter4, string Parameter5, string Parameter6, byte[] data) {
            return base.Channel.Magic(Action, UserID, Appname, PatientID, Token, Parameter1, Parameter2, Parameter3, Parameter4, Parameter5, Parameter6, data);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> MagicAsync(string Action, string UserID, string Appname, string PatientID, string Token, string Parameter1, string Parameter2, string Parameter3, string Parameter4, string Parameter5, string Parameter6, byte[] data) {
            return base.Channel.MagicAsync(Action, UserID, Appname, PatientID, Token, Parameter1, Parameter2, Parameter3, Parameter4, Parameter5, Parameter6, data);
        }
        
        public System.IO.Stream ReturnMagicJSON(MavenAsDemo.Unity.MagicInput o) {
            return base.Channel.ReturnMagicJSON(o);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> ReturnMagicJSONAsync(MavenAsDemo.Unity.MagicInput o) {
            return base.Channel.ReturnMagicJSONAsync(o);
        }
        
        public string GetSecurityToken(string Username, string Password) {
            return base.Channel.GetSecurityToken(Username, Password);
        }
        
        public System.Threading.Tasks.Task<string> GetSecurityTokenAsync(string Username, string Password) {
            return base.Channel.GetSecurityTokenAsync(Username, Password);
        }
        
        public string GetValidSecurityToken(string Username, string Password, string originalToken) {
            return base.Channel.GetValidSecurityToken(Username, Password, originalToken);
        }
        
        public System.Threading.Tasks.Task<string> GetValidSecurityTokenAsync(string Username, string Password, string originalToken) {
            return base.Channel.GetValidSecurityTokenAsync(Username, Password, originalToken);
        }
        
        public System.IO.Stream GetValidSecurityTokenPost(MavenAsDemo.Unity.GetTokenInput ti) {
            return base.Channel.GetValidSecurityTokenPost(ti);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetValidSecurityTokenPostAsync(MavenAsDemo.Unity.GetTokenInput ti) {
            return base.Channel.GetValidSecurityTokenPostAsync(ti);
        }
        
        public System.IO.Stream GetTokenJsonPost(MavenAsDemo.Unity.GetTokenJsonInput ti) {
            return base.Channel.GetTokenJsonPost(ti);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetTokenJsonPostAsync(MavenAsDemo.Unity.GetTokenJsonInput ti) {
            return base.Channel.GetTokenJsonPostAsync(ti);
        }
        
        public void RetireSecurityTokenPost(MavenAsDemo.Unity.RetireTokenInput ri) {
            base.Channel.RetireSecurityTokenPost(ri);
        }
        
        public System.Threading.Tasks.Task RetireSecurityTokenPostAsync(MavenAsDemo.Unity.RetireTokenInput ri) {
            return base.Channel.RetireSecurityTokenPostAsync(ri);
        }
        
        public void RetireTokenJsonPost(MavenAsDemo.Unity.RetireTokenJsonInput ri) {
            base.Channel.RetireTokenJsonPost(ri);
        }
        
        public System.Threading.Tasks.Task RetireTokenJsonPostAsync(MavenAsDemo.Unity.RetireTokenJsonInput ri) {
            return base.Channel.RetireTokenJsonPostAsync(ri);
        }
        
        public void RetireSecurityToken(string Token, string Appname) {
            base.Channel.RetireSecurityToken(Token, Appname);
        }
        
        public System.Threading.Tasks.Task RetireSecurityTokenAsync(string Token, string Appname) {
            return base.Channel.RetireSecurityTokenAsync(Token, Appname);
        }
    }
}
