#!/bin/bash
SYSNAME=$1
MACHINEREGION=$2
MACHINETYPE=$3
DEPLOYKEYFILE=$4
GITSERVERFINGERPRINTFILE=$5
WEBSERVERCRT=$6
WEBSERVERKEY=$7


if [ ! -z $MACHINETYPE ]; then
    # only create the instance in it a machinetype is passed in
    # Check to see if SYSNAME Instance already exists
    if gcloud compute instances list | grep "^..${SYSNAME} "; then
        echo instance $SYSNAME already exists
        exit 1
    fi

    # Create the Instance
    gcloud compute instances create $SYSNAME --zone $MACHINEREGION --machine-type $MACHINETYPE --image centos-7  --tags dev ssh
    if [ $? -eq 0 ]; then
        sleep 60
    else
        echo gcloud compute instances create $SYSNAME failed
        exit 1
    fi
fi

# Make sure that the Instance was created before trying to send the Setup Scripts
if ! (gcloud compute instances list | grep $SYSNAME) then
    echo gcloud compute instances list does not show instance $SYSNAME
    exit 1
fi

gcloud compute instances add-tags $SYSNAME --tags web

gcloud compute copy-files $DEPLOYKEYFILE $SYSNAME:~/deploy-key
gcloud compute copy-files $GITSERVERFINGERPRINTFILE $SYSNAME:~/github_server_fingerprint --zone $MACHINEREGION
gcloud compute copy-files $WEBSERVERCRT $SYSNAME:~/server.crt --zone $MACHINEREGION
gcloud compute copy-files $WEBSERVERKEY $SYSNAME:~/server.key --zone $MACHINEREGION

gcloud compute copy-files setup_scripts/common.sh setup_scripts/web_host_only.sh .bashrc maven.config nginx.base.conf nginx.conf $SYSNAME:~/ --zone $MACHINEREGION

gcloud compute ssh $SYSNAME --zone $MACHINEREGION --ssh-flag="-t" --command "bash common.sh"
gcloud compute ssh $SYSNAME --zone $MACHINEREGION --ssh-flag="-t" --command "bash web_host_only.sh"
