#!/bin/bash
SYSNAME=$1
if gcutil listinstances | grep "^..${SYSNAME} "; then
    echo instance $SYSNAME already exists
    exit 1
fi

gcutil addinstance $SYSNAME --zone="us-central1-f" --machine_type="g1-small" --network="default" --external_ip_address=ephemeral --image="centos-6" --persistent_boot_disk="true" --auto_delete_boot_disk="false" --tag="dev,ssh,web"
#gcutil addinstance $SYSNAME --zone="us-central1-f" --machine_type="f1-micro" --network="default" --external_ip_address=ephemeral --image="centos-6" --persistent_boot_disk="true" --auto_delete_boot_disk="false" --tag="dev,ssh,web" --disk="qa-frontend-1,deviceName=qa-frontend-1,mode=READ_WRITE,boot"

if [ $? -eq 0 ]; then
    sleep 60
else
    echo addinstance $SYSNAME failed
    exit 1
fi

if ! (gcutil listinstances | grep $SYSNAME) then
    echo listinstances does not show instance $SYSNAME
    exit 1
fi

gcutil push $SYSNAME /media/readyshare/public_keys/deploy-key /media/readyshare/public_keys/github_server_fingerprint .
gcutil push $SYSNAME /media/readyshare/public_keys/dev-server.crt server.crt
gcutil push $SYSNAME /media/readyshare/public_keys/dev-server.key server.key

gcutil push $SYSNAME common web_host_only ~/.bashrc .
gcutil push $SYSNAME ~/maven/app/schema .
echo "bash common" | gcutil ssh $SYSNAME 
echo "bash web_host_only" | gcutil ssh $SYSNAME
