#!/bin/bash

cd ~postgres
cd 9.3/data



sed -i.bak\
 -e 's/#ssl = .*/ssl = on/' \
 -e "s/#ssl_ciphers.*/ssl_ciphers = 'ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256'/" \
 -e "s/#ssl_ca_file.*/ssl_ca_file = 'cacert.pem'/" \
 -e "s/#ssl_cert_file.*/ssl_cert_file = 'server.crt'/" \
 -e "s/#ssl_key_file.*/ssl_key_file = 'server.key'/" \
postgresql.conf

echo "hostssl all postgres 0.0.0.0/0 cert clientcert=1 map=developer
hostssl maven maven 0.0.0.0/0 cert clientcert=1 map=developer" >> pg_hba.conf
echo "developer testing@mavenmedical.net postgres
developer testing@mavenmedical.net maven" >> pg_ident.conf

# need to put unencrypted server key (chmod 600) into data/server.key, also need server.crt and cacert.pem
# an encrypted key can be unencrypted by openssl rsa -in keyfile -out server.key