#!/bin/bash

cd $MAVEN_ROOT
UPDATESSQL=../schema_updates.sql
UPDATESLOG=../schema_updates.log
for f in `find app/database/updates/schema -name "*.sql"| sort -n` `find app/database/updates/data -name "*.sql"| sort -n`; do
  if grep -q "SUCCEEDED: $f" $UPDATESLOG; then
    echo $f succeeded in log
  else
    if grep -q "FAILED: $f" $UPDATESLOG; then
      echo $f previously failed?
      read -p "skip it (y/n)? " -n 1 -r
      echo
      if [[ ! $REPLY =~ ^[Nn]$ ]]; then
        echo skipping $f
        continue
      else
        exit 1
      fi
    fi
    echo "------------------`date`---------------">>$UPDATESSQL
    echo "------------------$f------------------">>$UPDATESSQL
    echo "M-----------------`date`---------------">>$UPDATESLOG
    echo "M-----------------$f---------------">>$UPDATESLOG
    psql -1 -v ON_ERROR_STOP=1 "`cat ~/.postgresql/command-line-connect`" -f $f >> $UPDATESLOG 2>&1
    if [ $? -eq 0 ]; then
      cat $f>>$UPDATESSQL
      echo M-----------------SUCCEEDED: $f------->>$UPDATESLOG
    else
      echo FAILED on $f
      echo M-----------------FAILED: $f------->>$UPDATESLOG
    fi
  fi
done
cd ~/maven/app/frontend_web/node && node r.js -o build.js
